---
title: Enviro-lunch Leveraging R
params:
  event: "Enviro-lunch!"
  date: "April 23, 2020"
  place: "Merced, California"
  title: "Leveraging R for your research"
  author: "Luna L. Sanchez Reyes"
  institute: "University of California, Merced"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu", "../ninjutsu-luna-extras.css", "assets/ninpo.css", "metropolis-fonts"]
    seal: false
    self_contained: false
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE)
options(knitr.duplicate.label = 'allow')
```
class: left, middle

# **`r params$title`**

<br/>

## Create your own website (and other things) using R!

<br/><br/><br/><br/>

### **`r params$author`**
### `r params$institute`
<br/><br/>

`r params$event`

`r params$date` &#183; `r params$place`

<br/>

Find the code for these slides [`r anicon::faa("github", animate="passing")` here](https://github.com/lunasare/slides/blob/master/leveraging-r-2020-04-20.Rmd).

---
class: split-20

.row[.content.vmiddle[
# The potential of R markdown `r emo::ji("raised_hands")`
]]
.row.split-four.white.font_medium[
.row.split-two.slide-in-left[
.column.bg-gray[.content.center[
Insert citations in any format with .font-mono[citr]
]]
.column.bg-black[.content.center[
Use paper templates for popular journals with .font-mono[rticles]
]]
]
.row.split-two.slide-in-right[
.column.bg-black[.content.center[
Generate word docs and de-render them bacl to R markdown with edits and tracjed changes, with .font-mono[redoc]
]]
.column.bg-gray[.content.center[
Create and maintain online books with .font-mono[bookdown]
]]
]
.row.split-two.slide-in-left[
.column.bg-gray[.content.center[
Build and maintain package and usage documentation with .font-mono[pkgdown]
]]
.column.bg-black[.content.center[
Organise an analysis project and construct a website for it with .font-mono[workflowr]
]]
]
.row.split-two.slide-in-right[
.column.bg-black[.content.center[
Create and maintain blogs and academic website with .font-mono[blogdown]
]]
.column.bg-gray[.content.center[
Create slide presentations with .font-mono[xaringan]
]]
]
]
